### ISSUE TITLE
Unable to import .blend and .fbx files, unable to load glTF and glb format

### ISSUE THREAD

**Issue by reinboa** [Silverlan/pfm#6]
I am unable to import any .blend or .fbx file into pragma as it doesn't detect those files. Also I am unable to load any glTF and glb format without it showing up as an error.

**Comment by Silverlan** [comment]
Can you please upload some of the files that it did not work with, and describe your steps, so I can try and replicate the issue?

**Comment by reinboa** [comment]
https://drive.google.com/file/d/1sXByVVdJSQDBY2iWPBXq5eOeE1Q1-k7W/view?usp=sharing
https://mega.nz/file/DeRjDAYY#k-GJD_ptacWdgaTVCJV_kKSblnzqdLrJ9nVjHDgkhF0
https://mega.nz/file/SX4nBLqK#t3bKCzuONZENqXjtndEaOSwlkFaORFiJxaRGThkgkAY
https://mega.nz/file/qaAyiJ5L#FYddR17Ufkx9w3EAKz6yjtwU8ldP-EvWqkIjlN10HXI

I first dragged and dropped the files in the model catalog like it says so in the wiki, however it makes a new folder and the file doesn't appear.

I converted the blend file in the google drive as both glTF and glb. PFM was able to load the materials, however when it comes to the actual model it just appears as an error.

**Comment by Silverlan** [comment]
Thanks! There were some issues with the glTF loader, which is why it didn't work properly. Fixed with the next update:
![pragma_4zVlkfnS0V](https://github.com/Silverlan/pfm/assets/3609960/9ef2477d-f80e-4387-95dc-fc0b7b9803f7)

The eyes are completely white, but it looks like that when importing the glb in Blender as well, so I'm assuming that's just the model.
